User.create(username: 'sheep', hashed_password: 'abcd', email: 'sheep@sheeprocks.com', role: 'admin')
User.create(username: 'joe', hashed_password: 'abcd', email: 'sheep@sheeprocks.com', role: 'admin')
User.create(username: 'paul', hashed_password: 'abcd', email: 'sheep@sheeprocks.com', role: 'admin')
User.create(username: 'jim', hashed_password: 'abcd', email: 'sheep@sheeprocks.com', role: 'admin')
User.create(username: 'marcy', hashed_password: 'abcd', email: 'sheep@sheeprocks.com', role: 'admin')
